name: Publish Python package

on:
  push:
    branches:
      - main  # publish on every commit to main

permissions:
  id-token: write   # required for PyPI Trusted Publisher
  contents: read    # needed to read repo code

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Publish to PyPI
        run: uv publish --trusted-publishing always